# Bridge with VLAN in access mode
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-eno49-policy
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: eno49
        description: Linux bridge with eno49 as a port
        ipv4:
          enabled: false
        name: br1
        state: up
        type: linux-bridge
