---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core<2.15
  galaxy:
    collections:
      - infra.osbuild
      - community.general
      - redhat.rhel_system_roles
      - edge.microshift
  python:
    - bindep
    - pyyaml
    - requirements-parser
    - jmespath

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

additional_build_files:
    - src: /home/cloud-user/workspace/ansible.cfg
      dest: config

additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg