---
version: 3

dependencies:
  galaxy:
    collections:
      - kubevirt.core
      - redhat.openshift
      - community.general
  python:
    - bindep
    - pyyaml
    - requirements-parser
    - jmespath

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest