apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: worker02-nmstate
  namespace: paris-dc1
spec:
  config:
    interfaces:
      - name: eth0
        type: ethernet
        state: up
        mac-address: 02:d6:b7:00:00:0c
        ipv4:
          enabled: true
          address:
            - ip: 192.168.10.11
              prefix-length: 24
          dhcp: false
    dns-resolver:
      config:
        server:
          - 8.8.8.8
          - 1.1.1.1
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.10.1
          next-hop-interface: eth0
          table-id: 254
  interfaces:
    - name: "eth0"
      macAddress: "02:d6:b7:00:00:0c"