FROM registry.redhat.io/devspaces/udi-rhel8

USER root

ENV TZ=Europe/Paris

RUN	\
	microdnf -y upgrade && \
    	microdnf install -y --enablerepo ansible-automation-platform-2.4-for-rhel-8-x86_64-rpms ansible-core ansible-navigator ansible-builder ansible-sign ansible-lint \
	git-core \
	podman \
	python3 \
	python3-markupsafe \
	python3-pip \
	python3-pyyaml \
	python3-wheel && \
	microdnf clean all && \
    	microdnf reinstall -y tzdata