---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: tech-talks-ocp-v
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
      - image: quay.io/rhdevelopers/food-service:latest
        name: bgd
        env:
        - name: COLOR
          value: "red"
        resources: {}
---
