apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  enableDownsampling: true
  observabilityAddonSpec:
    enableMetrics: true
    interval: 30
  storageConfig:
    alertmanagerStorageSize: 1Gi
    compactStorageSize: 20Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 20Gi
    ruleStorageSize: 1Gi
    storageClass: lvms-vg1
    storeStorageSize: 10Gi
  advanced:
    retentionConfig:
      retentionResolutionRaw: 365d
      retentionResolution5m: 365d
      retentionResolution1h: 365d
    receive: 
      replicas: 1
    alertmanager: 
      replicas: 1
    observatoriumAPI:
      replicas: 1
    queryFrontend:
      replicas: 1
    query:
      replicas: 1
    rule:
      replicas: 1
    store:
      replicas: 1
    CompactSpec:
      replicas: 1
    storeMemcached:
      replicas: 1
    queryFrontendMemcached:
      replicas: 1


