kind: ConfigMap
apiVersion: v1
metadata:
  name: devworkspace-gitconfig
  namespace: dmartini-redhat-com-devspaces-c71tba
data:
  gitconfig: |-
    [user] 
      name = dmartini 
      email = dmartini@redhat.com
