apiVersion: charts.helm.k8s.io/v1
kind: Xl
metadata:
  name: xl-release
  namespace: turbonomic
spec:
  global:
    customImageNames: false
    repository: icr.io/cpopen/turbonomic
    securityContext:
      fsGroup: 1001160000
    tag: 8.13.0
  nginx:
    nginxIsPrimaryIngress: false
    httpsRedirect: false
  nginxingress:
    enabled: true
  openshiftingress:
    enabled: true