hosts:
- hostname: master-1.rh.hpecic.net
  rootDeviceHints:
   deviceName: /dev/sdo
  interfaces:
   - macAddress: E0:07:1B:70:57:40
     name: eno49
  networkConfig:
    interfaces:
     - name: eno49
       type: ethernet
       state: up
       mac-address: E0:07:1B:70:57:40
       ipv4:
         enabled: true
         address:
           - ip: 10.6.187.11
             prefix-length: 23
         dhcp: false
    dns-resolver:
      config:
        server:
          - 10.6.186.5
          - 10.11.0.14
          - 10.11.0.13
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 10.6.187.1
          next-hop-interface: eno49
          table-id: 254
sshKey: "key"