apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-sda
  namespace: hcp01
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      name: 99-fake-nonrotational-sda
      labels:
        machineconfiguration.openshift.io/role: worker 
    spec:
      config:
        ignition:
          version: 3.2.0
        storage:
          files:
            - path: /etc/fake-nonrotational.sh
              mode: 0755
              contents:
                source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKZWNobyAwID4gL3N5cy9ibG9jay9zZGEvcXVldWUvcm90YXRpb25hbA==
        systemd:
          units:
            - name: fake-nonrotational.service
              enabled: true
              contents: |
                [Unit]
                Description=Force /dev/sda to be nonrotational
                After=local-fs.target
                Wants=local-fs.target

                [Service]
                Type=simple
                ExecStart=/etc/fake-nonrotational.sh
                Restart=always
                RestartSec=5s
                RemainAfterExit=true
                User=root

                [Install]
                WantedBy=multi-user.target