- name: Build RHDE image
  hosts: all
  gather_facts: false
  collections:
    - infra.osbuild
  tasks:

  - name: Add source for custom packages
    infra.osbuild.repository:
      repo_name: "Red Hat OpenShift Container Platform 4.16 for RHEL 9"
      base_url: https://cdn.redhat.com/content/dist/layered/rhel9/x86_64/rhocp/4.16/os
      type: yum-baseurl
      check_ssl: true
      check_gpg: true
      rhsm: true
      state: present

  