- name: Install and start image builder
  hosts: all
  gather_facts: false
  become: true

  tasks:

  - name: Deploy needed package
    ansible.builtin.dnf:
      name: 
        - osbuild-composer
        - composer-cli
        - podman
        - python3
        - python3-pip
        - python3-toml
        - python3-tomli
      state: present

  - name: Install multi python packages with version specifiers
    ansible.builtin.pip:
      name:
        - toml
        - pytoml
        - configparser

  - name: Start service osbuild-composer.socket, if not started
    ansible.builtin.service:
      name: osbuild-composer.socket
      state: started
      enabled: yes

  - name: Source file
    ansible.builtin.shell: source /etc/bash_completion.d/composer-cli

  - name: Restart service osbuild-composer
    ansible.builtin.service:
      name: osbuild-composer
      state: restarted
    
  - name: Show status
    ansible.builtin.shell: composer-cli status show
    register: composer_status

  - name: Print composer sattus
    ansible.builtin.debug:
      var: composer_status

  - name: Download virtctl cli
    ansible.builtin.get_url:
      url: https://hyperconverged-cluster-cli-download-openshift-cnv.apps.ocp.drkspace.fr/amd64/linux/virtctl.tar.gz
      dest: /tmp/virtctl.tar.gz
      mode: '0770'
      validate_certs : false

  - name: Extract virtctl cli
    ansible.builtin.unarchive:
      src: /tmp/virtctl.tar.gz
      dest: /tmp/virtctl

  - name: Changing perm virtclt, adding "+x"
    ansible.builtin.file: 
      path: /tmp/virtctl
      mode: 'a+x'