- name: Install and start image builder
  hosts: all
  gather_facts: false
  become: true

  tasks:

  - name: Deploy needed package
    ansible.builtin.dnf:
      name: 
        - osbuild-composer
        - composer-cli
        - podman
      state: present

  - name: Start service osbuild-composer.socket, if not started
    ansible.builtin.service:
      name: osbuild-composer.socket
      state: started
      enabled: yes

  - name: Source file
    ansible.builtin.shell: source /etc/bash_completion.d/composer-cli

  - name: Restart service osbuild-composer
    ansible.builtin.service:
      name: osbuild-composer
      state: restarted
    
  - name: Show status
    ansible.builtin.shell: composer-cli status show