---
- name: Install prosgreSQL with Lightspeed
  hosts: all
  become: true
  gather_facts: true
 
  tasks:
    # Install postgresql-server, postgresql and firewalld package on RHEL & initialize postgresql server & Enable services & start services & open firewall & create “ecommerce” database & create “user01” and “user02” users
    - name: Install postgresql-server, postgresql and firewalld package on RHEL
      when: ansible_os_family == "RedHat"
      ansible.builtin.package:
        name:
          - postgresql-server
          - postgresql
          - firewalld
        state: present

    - name: Initialize postgresql server
      ansible.builtin.command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Enable services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - postgresql
        - firewalld

    - name: Start services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - postgresql
        - firewalld

    - name: Open firewall
      ansible.posix.firewalld:
        port: 5432/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Create “ecommerce” database
      community.postgresql.postgresql_db:
        name: ecommerce
        state: present

    - name: Create “user01” and “user02” users
      community.postgresql.postgresql_user:
        name: "{{ item }}"
        password: "toto"
        db: ecommerce
        priv: ALL
        state: present
      loop:
        - user01
        - user02
    
    
    